default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: ${PIELATOR_DB_USERNAME}
  password: ${PIELATOR_DB_PASSWORD}
  pool: 5

development:
  <<: *default
  database: pielator_development


test:
  <<: *default
  database: pielator_test
